- name: Download and unpack prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: ~/
    remote_src: yes

- name: Copy prometheus binary to /bin
  copy:
    src: "prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /bin/prometheus
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    remote_src: yes

- name: Copy promtool binary to /bin
  copy:
    src: "prometheus-{{ prometheus_version }}.linux-amd64/promtool"
    dest: /bin/promtool
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    remote_src: yes

- name: Cleanup
  file:
    state: absent
    path: "~/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Copy prometheus service file
  register: prometheus_service
  template:
    src: "prometheus.service.j2"
    dest: "{{ systemd_dir }}/prometheus.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure prometheus config dir exists
  file:
    path: "{{ prometheus_dir }}"
    state: directory

- name: Copy prometheus config file
  template:
    src: "prometheus.yaml.j2"
    dest: "{{ prometheus_dir }}/prometheus.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Download and unpack node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: ~/
    remote_src: yes

- name: Copy node exporter binary to /bin
  copy:
    src: "node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /bin/node_exporter
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    remote_src: yes

- name: Cleanup
  file:
    state: absent
    path: "~/node_exporter-{{ node_exporter_version }}.linux-amd64"

- name: Copy node exporter service file
  register: node_exporter_service
  template:
    src: "node_exporter.service.j2"
    dest: "{{ systemd_dir }}/node_exporter.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Enable and check prometheus service
  systemd:
    name: prometheus
    daemon_reload: yes
    state: started
    enabled: yes
    no_block: yes

- name: Enable and check node exporter service
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes
    no_block: yes
