---
k3s_version: v1.22.3+k3s1
prometheus_version: 2.41.0
node_exporter_version: 1.5.0
ansible_user: root
systemd_dir: /etc/systemd/system
prometheus_dir: /etc/prometheus
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik"
extra_agent_args: ""
